# Generated by Django 5.0.3 on 2024-03-12 16:58

import urlapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(default=urlapp.models.generate_short_url, max_length=6, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UrlForm',
        ),
    ]
