# Generated by Django 5.0.3 on 2024-03-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
