# Generated by Django 5.0.3 on 2024-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0003_alter_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
